[mypy]
plugins = sqlalchemy.ext.mypy.plugin
ignore_missing_imports = True
explicit_package_bases = True
check_untyped_defs = False
disallow_untyped_defs = False
disable_error_code = arg-type, union-attr, return-value, index, call-overload, assignment, attr-defined, misc, operator
